$("#youth").load("departmentViews/youth.html")
$("#women").load("departmentViews/women.html")
$("#kbcusaMT").load("departmentViews/kbcusaMT.html")
$("#kbcusaED").load("departmentViews/kbcusaED.html")
$("#culture").load("departmentViews/culture.html")
$("#care").load("departmentViews/care.html")
$("#christianEd").load("departmentViews/christianEd.html")